trigger:
- main

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  pool:
    name: 'myagent'
  steps:
  - task: Ansible@0
    inputs:
      ansibleInterface: 'remoteMachine'
      connectionOverSsh: 'minio_aws'
      playbookSourceRemoteMachine: 'ansibleMachine'
      playbookPathAnsibleMachineOnRemoteMachine: 'ansible/playbooks'
      inventoriesRemoteMachine: 'file'
      inventoryFileSourceRemoteMachine: 'ansibleMachine'
      inventoryFileAnsibleMachineOnRemoteMachine: 'ansible/hosts.txt'