trigger:
- main

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  pool:
    name: 'default'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "Current working directory: $(pwd)"
         ls -l
  - task: Ansible@0
    inputs:
      ansibleInterface: 'agentMachine'
      playbookPathOnAgentMachine: 'ansible/playbooks/git_checkout.yml'
      inventoriesAgentMachine: 'file'
      inventoryFileOnAgentMachine: 'ansible/hosts.txt'
  