trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'minio_aws'
    playbookSourceRemoteMachine: 'ansibleMachine'
    playbookPathAnsibleMachineOnRemoteMachine: 'ansible/playbooks'
    inventoriesRemoteMachine: 'file'
    inventoryFileSourceRemoteMachine: 'ansibleMachine'
    inventoryFileAnsibleMachineOnRemoteMachine: 'ansible/hosts.txt'