trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.x'
    packageType: 'sdk'

- task: Ansible
  inputs:
    playbookPath: 'ansible/playbooks/git_checkout.yml'
    inventoryFile: 'hosts.txt'
  env:
    ANSIBLE_SSH_PRIVATE_KEY: $(ANSIBLE_SSH_PRIVATE_KEY)