trigger:
- main

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  pool:
    name: 'default'
  steps:
  - task: Ansible@0
    inputs:
      ansibleInterface: 'agentMachine'
      playbookPathOnAgentMachine: 'ansible/playbooks'
      inventoriesAgentMachine: 'file'
      inventoryFileOnAgentMachine: 'ansible/hosts.txt'