trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.x'
    packageType: 'sdk'

- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'minio_aws'
    playbookSourceRemoteMachine: 'ansibleMachine'
    playbookPathAnsibleMachineOnRemoteMachine: 'ansible/playbooks'
    inventoriesRemoteMachine: 'noInventory'